name: 'Deploy Template'

env:
  NUXT_SHOPIFY_NAME: ${{ secrets.NUXT_SHOPIFY_NAME }}
  NUXT_SHOPIFY_API_VERSION: ${{ secrets.NUXT_SHOPIFY_API_VERSION }}
  NUXT_SHOPIFY_STOREFRONT_PRIVATE_ACCESS_TOKEN: ${{ secrets.NUXT_SHOPIFY_STOREFRONT_PRIVATE_ACCESS_TOKEN }}

  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: |
          bun install --frozen-lockfile

  deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install Vercel CLI
        run: bun install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
