name: 'Lint'
on:
  pull_request:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --run "pnpm install --frozen-lockfile"
      - run: nix-shell --run "pnpm lint"
