name: 'Release'

on:
  create:
    branches:
      - main
    tags:
      - 'release'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: oven-sh/setup-bun@v2

      - name: Lint
        run: bun run lint

  typecheck:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: oven-sh/setup-bun@v2

      - name: Typecheck
        run: bun run typecheck

  release:
    runs-on: ubuntu-latest
    needs: [ install, lint, typecheck ]
    steps:
      - uses: oven-sh/setup-bun@v2

      - name: Build
        run: bun run build

      - name: Release module
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_CONFIG_TOKEN }}
        run: |
          bun run release || true
