name: 'Release Module'

env:
  NUXT_SHOPIFY_NAME: ${{ secrets.NUXT_SHOPIFY_NAME }}
  NUXT_SHOPIFY_API_VERSION: ${{ secrets.NUXT_SHOPIFY_API_VERSION }}
  NUXT_SHOPIFY_STOREFRONT_PUBLIC_ACCESS_TOKEN: ${{ secrets.NUXT_SHOPIFY_STOREFRONT_PUBLIC_ACCESS_TOKEN }}

on:
  create:
    branches:
      - main
    tags:
      - 'release'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Typecheck Module
        run: bun run typecheck

      - name: Typecheck Playground
        run: bun run typecheck:playground

      - name: Typecheck V4 Playground
        run: bun run typecheck:playground-v4

  release:
    runs-on: ubuntu-latest
    needs: [ lint, typecheck ]
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '22.17.1'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Release module
        run: |
          npm publish --provenance --no-git-checks || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_CONFIG_TOKEN }}
