name: 'Release'

on:
  create:
    branches:
      - main
    tags:
      - 'release'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Build
        run: pnpm build

      - name: Release module
        run: |
          pnpm set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          pnpm release
