name: 'Tests'

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: oven-sh/setup-bun@v2

      - name: Lint
        run: bun run lint

  typecheck:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: oven-sh/setup-bun@v2

      - name: Typecheck
        run: bun run typecheck
