name: 'Tests'

env:
  NUXT_SHOPIFY_NAME: ${{ secrets.NUXT_SHOPIFY_NAME }}
  NUXT_SHOPIFY_API_VERSION: ${{ secrets.NUXT_SHOPIFY_API_VERSION }}
  NUXT_SHOPIFY_STOREFRONT_PUBLIC_ACCESS_TOKEN: ${{ secrets.NUXT_SHOPIFY_STOREFRONT_PUBLIC_ACCESS_TOKEN }}

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint

      - name: Typecheck Module
        run: bun run typecheck

      - name: Typecheck Playground
        run: bun run typecheck:playground

      - name: Typecheck V4 Playground
        run: bun run typecheck:playground-v4
